title: HyphaMind
description: "HyphaMind: Composting for Cognitive Permaculture and Choral Emergence."
url: https://hyphamind.ai
baseurl: ""
timezone: UTC
markdown: kramdown
theme: null
plugins:
  - jekyll-redirect-from
  
# Social
twitter_handle: "@hyphamind_ai"

# External links
community_url: https://community.hyphamind.ai
whitepaper_url: https://github.com/hyphamind-ai/hyphaMind/blob/1722dfa36f3bb6a53bd4342606dfedb4a426bfc8/docs/vnext/whitepaper_vnext.md
